/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sccsimulator;

import javax.swing.JFrame;

/**
 *
 * @author Tomas
 */
public class GUI extends javax.swing.JFrame {

    private Simulador s;
    private int counter = 0;
    private boolean first = true;
    /**
     * Creates new form GUI
     */
    public GUI() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        media_prep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        desvio_prep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        seed_prep = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        atend_prep = new javax.swing.JTextField();
        seed_prep_label = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        atend_test = new javax.swing.JTextField();
        media_test = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        desvio_test = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        seed_test = new javax.swing.JSlider();
        seed_test_label = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        atend_fix = new javax.swing.JTextField();
        media_fix = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        desvio_fix = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        seed_fix = new javax.swing.JSlider();
        seed_fix_label = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tSimulacao = new javax.swing.JTextField();
        Simular = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        media_cheg = new javax.swing.JTextField();
        replicas = new javax.swing.JCheckBox();
        num_replicas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Média de chegada:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Preparação");

        media_prep.setText("6");
        media_prep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                media_prepActionPerformed(evt);
            }
        });

        jLabel6.setText("Média:");

        jLabel7.setText("Desvio padrão:");

        desvio_prep.setText("1.5");

        jLabel8.setText("Semente:");

        seed_prep.setMaximum(99);
        seed_prep.setPaintLabels(true);
        seed_prep.setValue(0);
        seed_prep.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                seed_prepMouseDragged(evt);
            }
        });
        seed_prep.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                seed_prepAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel9.setText("Máquinas:");

        atend_prep.setText("1");

        seed_prep_label.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(atend_prep, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(media_prep, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desvio_prep))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(seed_prep_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(seed_prep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(seed_prep_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seed_prep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desvio_prep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(media_prep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atend_prep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Teste");

        jLabel14.setText("Máquinas:");

        atend_test.setText("1");

        media_test.setText("4.5");
        media_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                media_testActionPerformed(evt);
            }
        });

        jLabel15.setText("Média:");

        jLabel16.setText("Desvio padrão:");

        desvio_test.setText("1.1");
        desvio_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desvio_testActionPerformed(evt);
            }
        });

        jLabel17.setText("Semente:");

        seed_test.setMaximum(99);
        seed_test.setValue(2);
        seed_test.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                seed_testMouseDragged(evt);
            }
        });

        seed_test_label.setText("2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(atend_test))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(media_test, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desvio_test))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(seed_test_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(seed_test, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(seed_test_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seed_test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desvio_test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(media_test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atend_test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Fixação");

        jLabel10.setText("Máquinas:");

        atend_fix.setText("1");

        media_fix.setText("5");
        media_fix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                media_fixActionPerformed(evt);
            }
        });

        jLabel11.setText("Média:");

        jLabel12.setText("Desvio padrão:");

        desvio_fix.setText("1.3");

        jLabel13.setText("Semente:");

        seed_fix.setMaximum(99);
        seed_fix.setValue(1);
        seed_fix.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                seed_fixMouseDragged(evt);
            }
        });

        seed_fix_label.setText("1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(atend_fix, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(media_fix, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 23, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desvio_fix))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(seed_fix_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(seed_fix, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(seed_fix_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seed_fix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desvio_fix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(media_fix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atend_fix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel18.setText("Tempo de Simulação:");

        tSimulacao.setText("40");

        Simular.setText("Simular");
        Simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimularActionPerformed(evt);
            }
        });

        jLabel22.setText("horas");

        media_cheg.setText("5");
        media_cheg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                media_chegActionPerformed(evt);
            }
        });

        replicas.setText("Réplicas");
        replicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replicasActionPerformed(evt);
            }
        });

        num_replicas.setText("3");
        num_replicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_replicasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tSimulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Simular, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(replicas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num_replicas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(media_cheg, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(Simular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tSimulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(replicas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num_replicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(media_cheg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void media_prepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_media_prepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_media_prepActionPerformed

    private void media_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_media_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_media_testActionPerformed

    private void media_fixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_media_fixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_media_fixActionPerformed

    private void SimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimularActionPerformed
         // Médias das distribuições de chegadas e de atendimento nos serviços
        double media_cheg = Double.parseDouble(this.media_cheg.getText());
        double media_prep = Double.parseDouble(this.media_prep.getText());
        double desvio_prep = Double.parseDouble(this.desvio_prep.getText());
        double media_fix = Double.parseDouble(this.media_fix.getText());
        double desvio_fix = Double.parseDouble(this.desvio_fix.getText());
        double media_test = Double.parseDouble(this.media_test.getText());
        double desvio_test = Double.parseDouble(this.desvio_test.getText());
        int seed_prep = this.seed_prep.getValue();
        int seed_fix = this.seed_fix.getValue();
        int seed_test = this.seed_test.getValue();
        int atend_prep = Integer.parseInt(this.atend_prep.getText());
        int atend_fix = Integer.parseInt(this.atend_fix.getText());
        int atend_test = Integer.parseInt(this.atend_test.getText());
        int tSimulacao = Integer.parseInt(this.tSimulacao.getText());
        double temp_med_fila_prep = 0;
        double comp_med_fila_prep = 0;
        double utilizacao_serv_prep = 0;
        double instante_prep = 0;
        double atendidos_prep = 0;
        double fila_prep = 0;
        
        double temp_med_fila_fix = 0;
        double comp_med_fila_fix = 0;
        double utilizacao_serv_fix = 0;
        double instante_fix = 0;
        double atendidos_fix = 0;
        double fila_fix = 0;
        
        double temp_med_fila_test = 0;
        double comp_med_fila_test = 0;
        double utilizacao_serv_test = 0;
        double instante_test = 0;
        double atendidos_test = 0;
        double fila_test = 0;
        
        
        if(!this.replicas.isSelected() && this.first == true)
        {  
            this.counter = 0;
            this.novaSimulacao(media_cheg, media_prep, desvio_prep, seed_prep, atend_prep, media_fix, desvio_fix, seed_fix, atend_fix, media_test, desvio_test, seed_test, atend_test, tSimulacao);
            this.first = false;
            return;
        }
        if(!this.replicas.isSelected() && this.first == false)
        {
            this.novaSimulacao(media_cheg, media_prep, desvio_prep, seed_prep, atend_prep, media_fix, desvio_fix, seed_fix, atend_fix, media_test, desvio_test, seed_test, atend_test, tSimulacao);
        }
        else
        {
            seed_prep = (int)(Math.random() * 100);
            seed_fix = (int)(Math.random() * 100);
            seed_test = (int)(Math.random() * 100);
            
            int simulacoes = Integer.parseInt(this.num_replicas.getText());
            for(int i = 0; i < simulacoes; i++)
            {
                // Cria um simulador e
                this.s = new Simulador(media_cheg, media_prep, desvio_prep, seed_prep, atend_prep, media_fix, desvio_fix, seed_fix, atend_fix, media_test, desvio_test, seed_test, atend_test, tSimulacao);

                // põe-o em marcha
                s.executa();
                s.relat();
                
                
                temp_med_fila_prep += this.s.dados_prep[0];
                comp_med_fila_prep += this.s.dados_prep[1];
                utilizacao_serv_prep += this.s.dados_prep[2];
                instante_prep += this.s.dados_prep[3];
                atendidos_prep += this.s.dados_prep[4];
                fila_prep += this.s.dados_prep[5];
                
                
                temp_med_fila_fix += this.s.dados_fix[0];
                comp_med_fila_fix += this.s.dados_fix[1];
                utilizacao_serv_fix += this.s.dados_fix[2];
                instante_fix += this.s.dados_fix[3];
                atendidos_fix += this.s.dados_fix[4];
                fila_fix += this.s.dados_fix[5];
                
                temp_med_fila_test += this.s.dados_test[0];
                comp_med_fila_test += this.s.dados_test[1];
                utilizacao_serv_test += this.s.dados_test[2];
                instante_test += this.s.dados_test[3];
                atendidos_test += this.s.dados_test[4];
                fila_test += this.s.dados_test[5];
            }
            
            temp_med_fila_prep /= simulacoes;
            comp_med_fila_prep /= simulacoes;
            utilizacao_serv_prep /= simulacoes;
            instante_prep /= simulacoes;
            atendidos_prep /= simulacoes;
            fila_prep /= simulacoes;

            temp_med_fila_fix /= simulacoes;
            comp_med_fila_fix /= simulacoes;
            utilizacao_serv_fix /= simulacoes;
            instante_fix /= simulacoes;
            atendidos_fix /= simulacoes;
            fila_fix /= simulacoes;

            temp_med_fila_test /= simulacoes;
            comp_med_fila_test /= simulacoes;
            utilizacao_serv_test /= simulacoes;
            instante_test /= simulacoes;
            atendidos_test /= simulacoes;
            fila_test /= simulacoes;
            
            String result_prep = "\nTempo médio de espera "+temp_med_fila_prep
                +"\nComp. médio da fila "+comp_med_fila_prep
                +"\nUtilização do serviço "+utilizacao_serv_prep
                +"\nTempo de simulação "+instante_prep
                +"\nNúmero de clientes atendidos "+atendidos_prep
                +"\nNúmero de clientes na fila "+fila_prep;
            
            String result_fix = "\nTempo médio de espera "+temp_med_fila_fix
                +"\nComp. médio da fila "+comp_med_fila_fix
                +"\nUtilização do serviço "+utilizacao_serv_fix
                +"\nTempo de simulação "+instante_fix
                +"\nNúmero de clientes atendidos "+atendidos_fix
                +"\nNúmero de clientes na fila "+fila_fix;
            
            String result_test = "\nTempo médio de espera "+temp_med_fila_test
                +"\nComp. médio da fila "+comp_med_fila_test
                +"\nUtilização do serviço "+utilizacao_serv_test
                +"\nTempo de simulação "+instante_test
                +"\nNúmero de clientes atendidos "+atendidos_test
                +"\nNúmero de clientes na fila "+fila_test;
            
            String final_text;
            
            if(!this.atend_test.getText().equals("0"))
            {
                final_text = "\n------- Resultados preparacao -------\n"
                    +result_prep
                    +"\n\n------- Resultados fixacao -------\n"
                    +result_fix
                    +"\n\n------- Resultados teste -------\n"
                    +result_test;
            }
            else
            {
                final_text = "\n------- Resultados preparacao -------\n"
                    +result_prep
                    +"\n\n------- Resultados fixacao -------\n"
                    +result_fix;
            }                
            
            
            String[] info = new String[2];
            info[0] = final_text;
            
            info[1] = ""+simulacoes;
                    
            Result.main(info);
            
            this.first = true;            
        }
    }//GEN-LAST:event_SimularActionPerformed

    private void novaSimulacao(double media_cheg, double media_prep, double desvio_prep, int seed_prep, int atend_prep, double media_fix, double desvio_fix, int seed_fix, int atend_fix, double media_test, double desvio_test, int seed_test, int atend_test, int tSimulacao)
    {
        // Cria um simulador e
        this.s = new Simulador(media_cheg, media_prep, desvio_prep, seed_prep, atend_prep, media_fix, desvio_fix, seed_fix, atend_fix, media_test, desvio_test, seed_test, atend_test, tSimulacao);

        // põe-o em marcha
        s.executa();

        String[] info = new String[2];
        info[0] = s.relat();

        this.counter++;
        info[1] = ""+this.counter;


        Result.main(info);
    }
    
    private void desvio_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desvio_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desvio_testActionPerformed

    private void seed_prepAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_seed_prepAncestorMoved
        
    }//GEN-LAST:event_seed_prepAncestorMoved

    private void seed_prepMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seed_prepMouseDragged
        this.seed_prep_label.setText(String.valueOf(this.seed_prep.getValue()));
    }//GEN-LAST:event_seed_prepMouseDragged

    private void seed_fixMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seed_fixMouseDragged
        this.seed_fix_label.setText(String.valueOf(this.seed_fix.getValue()));
    }//GEN-LAST:event_seed_fixMouseDragged

    private void seed_testMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seed_testMouseDragged
        this.seed_test_label.setText(String.valueOf(this.seed_test.getValue()));
    }//GEN-LAST:event_seed_testMouseDragged

    private void media_chegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_media_chegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_media_chegActionPerformed

    private void replicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replicasActionPerformed

    private void num_replicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_replicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_replicasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Simular;
    private javax.swing.JTextField atend_fix;
    private javax.swing.JTextField atend_prep;
    private javax.swing.JTextField atend_test;
    private javax.swing.JTextField desvio_fix;
    private javax.swing.JTextField desvio_prep;
    private javax.swing.JTextField desvio_test;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField media_cheg;
    private javax.swing.JTextField media_fix;
    private javax.swing.JTextField media_prep;
    private javax.swing.JTextField media_test;
    private javax.swing.JTextField num_replicas;
    private javax.swing.JCheckBox replicas;
    private javax.swing.JSlider seed_fix;
    private javax.swing.JLabel seed_fix_label;
    private javax.swing.JSlider seed_prep;
    private javax.swing.JLabel seed_prep_label;
    private javax.swing.JSlider seed_test;
    private javax.swing.JLabel seed_test_label;
    private javax.swing.JTextField tSimulacao;
    // End of variables declaration//GEN-END:variables
}
